services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
        - 5432:5432
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db-test:
    image: postgres
    container_name: db-test
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    extra_hosts:
      - "host.docker.internal:host-gateway"

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      TEST_DATABASE_URL: "host=host.docker.internal port=5433 user=postgres password=postgres dbname=postgres sslmode=disable"
      DATABASE_URL: "host=host.docker.internal port=5432 user=postgres password=postgres dbname=postgres sslmode=disable"
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
